# Copyright (c) 2020 The ZMK Contributors
# SPDX-License-Identifier: MIT

# --- SLEEP SETTINGS ---
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=6000000
CONFIG_ZMK_PM_SOFT_OFF=y

# --- COMBO SETTINGS ---
CONFIG_ZMK_COMBO_MAX_PRESSED_COMBOS=8

# --- BLE SETTINGS ---
CONFIG_BT_MAX_PAIRED=6
CONFIG_BT_MAX_CONN=6

# --- USB SETTINGS ---
CONFIG_ZMK_BLE=n
CONFIG_USB_DEVICE_PID=0x641E
CONFIG_BT_DIS_PNP_PID=0x641E

# --- EXPERIMENTAL ---
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y
CONFIG_ZMK_STUDIO_LOCKING=n
