---
include:
  - board:  nice_nano_v2
    shield: nine_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board:  nice_nano_v2
    shield: nine_right
  - board:  seeeduino_xiao_ble
    shield: zaphod_lite
  # - board: nice_nano_v2
  #   shield: cradio_left
  # - board: nice_nano_v2
  #   shield: cradio_right
  # - board: nice_nano_v2
  #   shield: reviung41
  # - board: sparkfun_pro_micro_rp2040
  #   shield: reviung41
  # - board: nice_nano_v2
  #   shield: corne_left
  # - board: nice_nano_v2
  #   shield: corne_right
  # - board: nice_nano_v2
  #   shield: settings_reset
