# Copyright (c) 2020 The ZMK Contributors
# SPDX-License-Identifier: MIT

# --- DISPLAY SETTINGS ---
CONFIG_ZMK_DISPLAY=n
CONFIG_ZMK_WIDGET_WPM_STATUS=n

# --- SLEEP SETTINGS ---
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=6000000
CONFIG_ZMK_PM_SOFT_OFF=y

# --- COMBO SETTINGS ---
CONFIG_ZMK_COMBO_MAX_PRESSED_COMBOS=8

# --- BLE SETTINGS ---
CONFIG_BT_MAX_PAIRED=6
CONFIG_BT_MAX_CONN=6

# --- USB SETTINGS ---
CONFIG_USB_DEVICE_PID=0x645F
CONFIG_BT_DIS_PNP_PID=0x645F

